"""add analysis detail cache columns

Revision ID: f4733a0b8caa
Revises: 0002
Create Date: 2026-06-25 00:28:15.004843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4733a0b8caa'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis', sa.Column('top_errors_json', sa.Text(), nullable=True))
    op.add_column('analysis', sa.Column('eval_sequence_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis', 'eval_sequence_json')
    op.drop_column('analysis', 'top_errors_json')
    # ### end Alembic commands ###
